# Setup a redirect from one apex domain to another
# For example: redirect all traffic from my-site.org to mysite.org
# This template is based on https://repost.aws/knowledge-center/redirect-domain-route-53
# It currently only works in us-east-1 region
AWSTemplateFormatVersion: 2010-09-09
Description: Setup redirect from one apex domain to another using S3 static website redirect
Parameters:
  SourceHostName:
    Description: The source endpoint (to redirect from)
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name (i.e. my-site.org).
  SourceHostedZoneId:
    Description: The ID of the hosted zone of the source domain. Needs to be in the same account.
    Type: String
    MaxLength: 32
    AllowedPattern: "[A-Z0-9]*"
    ConstraintDescription: Must be a valid hosted zone ID
    Default: ""
  TargetHostName:
    Description: The target endpoint
    Type: String
    AllowedPattern: (?!-)[a-zA-Z0-9-.]{1,63}(?<!-)
    ConstraintDescription: must be a valid DNS zone name (i.e. mysite.org).
Conditions:
  HasHostedZoneId: !Not [ !Equals [ "", !Ref SourceHostedZoneId ] ]
Mappings:
  # S3 Website endpoints, see https://docs.aws.amazon.com/general/latest/gr/s3.html
  S3WebsiteEndpoints:
    us-east-1:
      Endpoint: "s3-website-us-east-1.amazonaws.com"
      HostedZoneId: "Z3AQBSTGFYJSTF"
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced
      BucketName: !Ref SourceHostName
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Ref TargetHostName
          Protocol: https
  DnsRecord:
    Condition: HasHostedZoneId
    DependsOn: Bucket
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref SourceHostName
      Type: A
      Region: !Sub '${AWS::Region}'
      HostedZoneId: !Ref SourceHostedZoneId
      SetIdentifier: !Sub '${AWS::StackName}'
      AliasTarget:
        DNSName: !FindInMap [S3WebsiteEndpoints, !Ref "AWS::Region", Endpoint]
        EvaluateTargetHealth: true
        HostedZoneId: !FindInMap [S3WebsiteEndpoints, !Ref "AWS::Region", HostedZoneId]
Outputs:
  BucketWebsiteUrl:
    Value: !GetAtt Bucket.WebsiteURL
    Description: URL for redirector
    Export:
      Name: !Sub '${AWS::StackName}-BucketWebsiteUrl'
  WebsiteBucket:
    Value: !Ref Bucket
    Description: The bucket containing the website redirect
    Export:
      Name: !Sub '${AWS::StackName}-WebsiteBucket'
